In [16]:
import numpy as np

In [29]:
def calculate(list):
    #Exception Handling
    new_mat = np.array(list)
    try:
        new_mat = new_mat.reshape(3,3)
        print(new_mat)
    except ValueError:
        raise ValueError ('List must contain nine numbers.') from None
    listDict = {}
    for i in range(12):
        listDict[f'lt_{i}']=[]
    for i in range(0,3):
        x=new_mat[i,:]
        y=new_mat[:,i]        
        listDict['lt_0'].append(x.mean())
        listDict['lt_1'].append(y.mean())
        listDict['lt_2'].append(x.var())
        listDict['lt_3'].append(y.var())
        listDict['lt_4'].append(x.std())
        listDict['lt_5'].append(y.std())
        listDict['lt_6'].append(x.max())
        listDict['lt_7'].append(y.max())
        listDict['lt_8'].append(x.min())
        listDict['lt_9'].append(y.min())
        listDict['lt_10'].append(x.sum())
        listDict['lt_11'].append(y.sum())
    mat_mean = [listDict['lt_1'], listDict['lt_0'], new_mat.mean()]
    mat_var=[listDict['lt_3'], listDict['lt_2'], new_mat.var()]
    mat_std = [listDict['lt_5'], listDict['lt_4'], new_mat.std()]
    mat_max = [listDict['lt_7'], listDict['lt_6'], new_mat.max()]
    mat_min = [listDict['lt_9'], listDict['lt_8'], new_mat.min()]
    mat_sum = [listDict['lt_11'], listDict['lt_10'], new_mat.sum()]
    output = {
        'mean': mat_mean,
        'variance': mat_var,
        'standard deviation': mat_std,
        'max': mat_max,
        'min': mat_min,
        'sum': mat_sum
      }
    return output

In [30]:
calculate([2,6,2,8,4,0,1,5,7])

[[2 6 2]
 [8 4 0]
 [1 5 7]]


{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}